export type GameLocale = "ko" | "en";

export const GAME_CONFIG = {
  slug: "monkey-bananas",
  creator: "Manse",
  sourceUrl: "https://github.com/ahndohun/manse-game-monkey-bananas",
  defaultLocale: "en" as GameLocale,
  heroUrl: "/packs/monkey-bananas/assets/images/jungle-jump-hero.png",
} as const;

export const UI_COPY = {
  ko: {
    pageTitle: "원숭이 바나나",
    summary: "정글 친구와 함께 가볍게 뛰어 나무에 매달린 바나나 다섯 송이를 따 보세요.",
    kicker: "독립형 Manse 게임",
    localeLabel: "언어 선택",
    korean: "한국어",
    english: "영어",
    heroAlt: "햇살이 비치는 정글에서 작은 원숭이가 나뭇가지의 노란 바나나를 향해 뛰어오르는 그림",
    privacy: "카메라 영상은 이 기기에만 머물러요 · 계정 없음 · 분석 도구 없음",
    playerLabel: "원숭이 바나나 게임 플레이어",
    stageLabel: "점프 동작 게임 무대",
    startHelp: "먼저 포인터로 연습해 보세요. 카메라는 선택 사항이며 버튼을 누른 뒤에만 권한을 요청합니다.",
    playPointer: "포인터로 시작",
    useCamera: "카메라로 시작",
    restartPointer: "포인터로 다시 시작",
    switchCamera: "카메라로 전환",
    comfort: "주변을 정리하고 편안한 공간에서 플레이하세요.",
    statusAttention: "확인이 필요해요",
    statusStarting: "시작하는 중",
    statusComplete: "완료",
    statusChoose: "플레이 방법을 선택하세요",
    statusCamera: "카메라 영상은 기기에만 저장돼요",
    statusSimulator: "포인터 모드 실행 중",
    missionSpec: "정글 구역 3곳 · 바나나 5송이",
    progressLabel: "바나나 진행도",
    startError: "게임을 시작하지 못했어요. 다시 시도하거나 포인터 모드를 선택해 주세요.",
    footer: "Manse가 만들고 오픈 Manse 엔진으로 실행합니다. 움직임이 불편하면 언제든 멈추세요.",
    source: "소스 보기",
  },
  en: {
    pageTitle: "Monkey Bananas",
    summary: "Leap through the jungle with a cheerful friend and collect five bananas hanging in the tree.",
    kicker: "Independent Manse game",
    localeLabel: "Choose language",
    korean: "Korean",
    english: "English",
    heroAlt: "A little monkey leaps toward bright yellow bananas in a sunlit jungle canopy",
    privacy: "Camera stays on this device · no account · no analytics",
    playerLabel: "Monkey Bananas game player",
    stageLabel: "Interactive jumping game stage",
    startHelp: "Start with the pointer to practice. Camera mode is optional and asks permission only after you choose it.",
    playPointer: "Play with pointer",
    useCamera: "Use my camera",
    restartPointer: "Restart with pointer",
    switchCamera: "Switch to camera",
    comfort: "Choose a private, comfortable play space.",
    statusAttention: "Needs attention",
    statusStarting: "Starting",
    statusComplete: "Complete",
    statusChoose: "Choose how to play",
    statusCamera: "Camera stays on device",
    statusSimulator: "Simulator live",
    missionSpec: "3 canopy zones · 5 bananas",
    progressLabel: "Banana progress",
    startError: "The game could not start. Please try again or choose pointer mode.",
    footer: "Created by Manse and powered by the open Manse engine. Stop whenever movement feels uncomfortable.",
    source: "View source",
  },
} as const satisfies Record<GameLocale, Record<string, string>>;
